version: '2'
services:
  odm-deployer:
    container_name: odm-deployer
    image: smartcontract/odm-deployer:1.0.0
    build: 
      context: ./
      dockerfile: ./Dockerfile
    ports:
    - 1880:1880

networks:
  default:
    external:
      name: composer_default
   
    
